repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.9
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix, --line-length=100 ]
    # Run the formatter.
    - id: ruff-format
      args: [--line-length=100]